# Generated by Django 3.1.5 on 2021-01-19 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo')),
                ('editorial', models.CharField(max_length=100, verbose_name='Editorial')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('paginas', models.IntegerField(verbose_name='Paginas')),
                ('ISBN', models.CharField(max_length=20, verbose_name='ISBN')),
                ('nroEdicion', models.IntegerField(verbose_name='N° Edición')),
                ('reseña', models.TextField(verbose_name='Reseña')),
                ('categoria', models.CharField(choices=[('1', 'Romance'), ('2', 'Acción'), ('3', 'Aventura'), ('4', 'Comedia')], max_length=1, verbose_name='Categoría')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.autor', verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='images/', verbose_name='Imagen')),
                ('estado', models.BooleanField(verbose_name='Estado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.libro', verbose_name='Libro')),
            ],
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('D', 'Digital'), ('F', 'Fisico')], max_length=1, verbose_name='Formato')),
                ('idioma', models.CharField(max_length=50, verbose_name='Idioma')),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('P', 'Prestamo'), ('M', 'Mantención')], max_length=1, verbose_name='Estado')),
                ('entrega', models.DateField(verbose_name='Fecha Entrega')),
                ('devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha Devolución')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.libro', verbose_name='Libro')),
            ],
        ),
    ]
