# Generated by Django 3.1 on 2021-01-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_existencia_galeria_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existencia',
            name='entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Entrega'),
        ),
    ]
